const menu = [
  {
    id: 1,
    catagoryName: "Starter",
    itemName: "Achari Paneer Tikka",
    discription:
      "Indian cheese cooked in a clay oven, served with onions & green pepper",
    imgUrl: "",
    price: 5.95,
  },
  {
    id: 2,
    catagoryName: "Starter",
    itemName: "Bhalla Papari Chaat",
    discription:
      "Crispy wheat & lentil dumplings dipped in yoghurt & tamarind chutney. A famous roadside snack of Old Delhi Bazaar - Served cold.",
    imgUrl: "",
    price: 5.5,
  },
  {
    id: 3,
    catagoryName: "Starter",
    itemName: "Buffalo King Prawns",
    discription: "Deep fried king prawns dipped in breadcrumbs & sesame seeds.",
    imgUrl: "",
    price: 5.5,
  },
  {
    id: 4,
    catagoryName: "Starter",
    itemName: "Chicken Chat Puree",
    discription:
      "Boneless chicken cooked with exotic spices, served with deep fried bread.",
    imgUrl: "/images/Chicken-Chat-Puree.jpg",
    price: 4.95,
  },
  {
    id: 5,
    catagoryName: "Starter",
    itemName: "Chicken Tandoori Tikka",
    discription: "Tnadoori chicken cooked with exotic spices",
    imgUrl: "/images/chicken-tandoori-tikka.jpg",
    price: 4.75,
  },
  {
    id: 6,
    catagoryName: "Starter",
    itemName: "Chicken Tikka Starter",
    discription: "Boneless chicken cooked with exotic spices",
    imgUrl: "/images/chicken-tikka-starter.jpg",
    price: 4.75,
  },
  {
    id: 7,
    catagoryName: "Starter",
    itemName: "Crab Cake",
    discription:
      "Crab meat marinated with onion, peppers & coriander, coated in breadcrumbs & sesame seed",
    imgUrl: "/images/crabe-cake.jpg",
    price: 6.5,
  },
  {
    id: 8,
    catagoryName: "Starter",
    itemName: "Fish Masala Fry ",
    discription: "Catch of the day fish, coated with batter & deep fried",
    imgUrl: "",
    price: 5.5,
  },
  {
    id: 9,
    catagoryName: "Starter",
    itemName: "Gol Guppa",
    discription:
      "Stuffed puff pastries served with creamy yoghurt, chickpeas, potatoes & coriander & mint chutney - Served cold",
    imgUrl: "",
    price: 5.95,
  },
  {
    id: 10,
    catagoryName: "Starter",
    itemName: "Hariyali Chicken Tikka",
    discription:
      "Made with boneless chicken blended and cooked in fresh green herbs and spices made of fresh mint leaves, coriander leaves and green chillies.",
    imgUrl: "",
    price: 4.75,
  },
  {
    id: 11,
    catagoryName: "Starter",
    itemName: "King Prawn Puree",
    discription: "Served with Deep Fried Bread",
    imgUrl: "",
    price: 7.0,
  },
  {
    id: 12,
    catagoryName: "Starter",
    itemName: "Lamb Samosa Starter",
    discription: "Mince meat wrapped in a triangular pastry",
    imgUrl: "/images/lamb-samosa-statar.jpg",
    price: 4.5,
  },
  {
    id: 13,
    catagoryName: "Starter",
    itemName: "Lamb Seekh Kebab",
    discription: "Minced lamb cooked on a skewer",
    imgUrl: "/images/Lamb-Seekh-Kebab.jpg",
    price: 4.95,
  },
  {
    id: 14,
    catagoryName: "Starter",
    itemName: "Masha Bhara",
    discription:
      "Mackerel fish, hint of green chilli, lemon grass, onions and spinach.",
    imgUrl: "",
    price: 5.95,
  },
  {
    id: 15,
    catagoryName: "Starter",
    itemName: "Minted Lamb Tikka",
    discription: "Minted Lamb Tikka cooked on a skewer",
    imgUrl: "/images/Minted-Lamb-Tikka.jpg",
    price: 4.95,
  },
  {
    id: 16,
    catagoryName: "Starter",
    itemName: "Mixed Platter",
    discription:
      "Sharing for two, chicken tikka, malai tikka, seekh kebab & fish pakora",
    imgUrl: "",
    price: 10.95,
  },
  {
    id: 16,
    catagoryName: "Starter",
    itemName: "Murg Malai Tikka Starter",
    discription:
      "Boneless chicken, marinated with ginger, garlic, cheddar cheese & fresh cream",
    imgUrl: "/images/murag-mali-tikka-starter.jpg",
    price: 4.75,
  },
  {
    id: 17,
    catagoryName: "Starter",
    itemName: "Mussels (New Zealand)",
    discription: "Mussels (New Zealand)",
    imgUrl: "",
    price: 6.5,
  },
  {
    id: 18,
    catagoryName: "Starter",
    itemName: "Onion Bhaji ",
    discription: "Onion Bhaji ",
    imgUrl: "",
    price: 3.95,
  },
  {
    id: 18,
    catagoryName: "Starter",
    itemName: "Prawn Puree ",
    discription: "Marinated with exotic spices & cooked in a clay oven ",
    imgUrl: "",
    price: 7.5,
  },
  {
    id: 19,
    catagoryName: "Starter",
    itemName: "Scallops",
    discription: "Toasted in butter served with chefs special sauce & salad",
    imgUrl: "",
    price: 7.5,
  },
  {
    id: 20,
    catagoryName: "Starter",
    itemName: "Soft Shell Crab",
    discription: "Cooked with exotic spices & served crispy",
    imgUrl: "",
    price: 6.5,
  },
  {
    id: 21,
    catagoryName: "Starter",
    itemName: "Sweet Chilli Chicken Starter",
    discription:
      "Old Delhi street stall style chicken in a sauce of chilli & garlic, served with peppers & spring onions",
    imgUrl: "/images/Sweet-Chilli-Chicken-Starter.jpg",
    price: 4.95,
  },
  {
    id: 21,
    catagoryName: "Starter",
    itemName: "Sweet Chilli King Prawns ",
    discription:
      "Old Delhi street stall style prawns in a sauce of chilli & garlic, served with peppers & spring onions",
    imgUrl: "",
    price: 6.95,
  },
  {
    id: 22,
    catagoryName: "Starter",
    itemName: "Tandoori Lamb chop",
    discription: "Tandoori Lamb chop",
    imgUrl: "",
    price: 6.95,
  },
  {
    id: 23,
    catagoryName: "Starter",
    itemName: "Vegetable Samosa Starter",
    discription: "Vegetables wrapped in a triangular pastry",
    imgUrl: "",
    price: 4.0,
  },
  {
    id: 24,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Chicken (Half)",
    discription:
      "Spring chicken on the bone, marinated & grilled in the tandoori oven. Served with salad.",
    imgUrl: "",
    price: 9.5,
  },
  {
    id: 25,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Chicken Shashlik",
    discription:
      "Chicken with tomatoes, green pepper & onion cooked in the clay oven. Served with salad.",
    imgUrl: "",
    price: 11.95,
  },
  {
    id: 26,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Chicken Tikka ",
    discription: "Tandoori Chicken Tikka ",
    imgUrl: "",
    price: 9.5,
  },
  {
    id: 27,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Delight",
    discription:
      "Boneless lamb & chicken cooked with pepper & onion in the clay oven, fried in butter, served as a sizzling dish.",
    imgUrl: "",
    price: 12.5,
  },
  {
    id: 28,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Hariyali Chicken Tikka ",
    discription:
      "Made with boneless chicken blended and cooked in fresh green herbs and spices made of fresh mint leaves, coriander leaves and green chillies. Served with salad",
    imgUrl: "",
    price: 9.5,
  },
  {
    id: 29,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori King Prawn Shashlick",
    discription:
      "King prawns with tomatoes, green pepper & onion cooked in the clay oven. Served with salad",
    imgUrl: "",
    price: 13.95,
  },
  {
    id: 30,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Lamb Shaslick",
    discription:
      "Lamb with tomatoes, green pepper & onion cooked in the clay oven. Served with salad",
    imgUrl: "",
    price: 12.95,
  },
  {
    id: 31,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Lamb Tikka",
    discription: "Tandoori Lamb Tikka",
    imgUrl: "",
    price: 10.5,
  },
  {
    id: 32,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Mixed Grill",
    discription:
      "Chicken tikka, seekh kebab, lamb tikka, tandoori chicken, tandoori king prawn. Served with salad",
    imgUrl: "",
    price: 14.5,
  },
  {
    id: 33,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Murg Malai Tikka",
    discription:
      "Boneless chicken, marinated with ginger, garlic, cheddar cheese & fresh cream",
    imgUrl: "",
    price: 9.5,
  },
  {
    id: 33,
    catagoryName: "Tandoori Dishes",
    itemName: "Tandoori Salmon Tikka",
    discription:
      "Pieces of salmon cooked in the clay oven with exotic spices. Served with salad",
    imgUrl: "",
    price: 14.5,
  },
  {
    id: 34,
    catagoryName: "Biryani Dishes",
    itemName: "Chicken Biryani ",
    discription: "Chicken Biryani",
    imgUrl: "/images/Chicken-Biryani.jpg",
    price: 11.95,
  },
  {
    id: 35,
    catagoryName: "Biryani Dishes",
    itemName: "Chicken Tikka Biryani  ",
    discription: "Chicken Tikka Biryani ",
    imgUrl: "/images/Chicken-Tikka-Biryani.jpg",
    price: 12.95,
  },
  {
    id: 36,
    catagoryName: "Biryani Dishes",
    itemName: "King Prawn Biryani",
    discription: "King Prawn Biryani",
    imgUrl: "/images/King-Prawn-Biryani.jpg",
    price: 13.95,
  },
  {
    id: 37,
    catagoryName: "Biryani Dishes",
    itemName: "Lamb Biryani",
    discription: "Lamb Biryani",
    imgUrl: "/images/Lamb-Biryani.jpg",
    price: 12.95,
  },
  {
    id: 38,
    catagoryName: "Biryani Dishes",
    itemName: "Lamb Tikka Biryani",
    discription: "Lamb Tikka Biryani",
    imgUrl: "/images/Lamb-Tikka-Biryani.jpg",
    price: 13.95,
  },
  {
    id: 39,
    catagoryName: "Biryani Dishes",
    itemName: "Prawn Biryani",
    discription: "Prawn Biryani",
    imgUrl: "/images/Prawn-Biryani.jpg",
    price: 12.95,
  },
  {
    id: 40,
    catagoryName: "Biryani Dishes",
    itemName: "Special Mix Biryani",
    discription: "Special Mix Biryani",
    imgUrl: "/images/Special-Mix-Biryani.jpg",
    price: 14.5,
  },
  {
    id: 41,
    catagoryName: "Biryani Dishes",
    itemName: "Vegetable Biryani",
    discription: "Vegetable Biryani",
    imgUrl: "/images/Vegetable-Biryani.jpg",
    price: 10.95,
  },
  {
    id: 42,
    catagoryName: "Rice Dishes",
    itemName: "Chicken Tikka Rice",
    discription: "Chicken Tikka Rice",
    imgUrl: "/images/Chicken-Tikka-Rice.jpg",
    price: 4.5,
  },
  {
    id: 43,
    catagoryName: "Rice Dishes",
    itemName: "Coconut Rice",
    discription: "Coconut Rice",
    imgUrl: "/images/Coconut-Rice.gif",
    price: 3.95,
  },
  {
    id: 44,
    catagoryName: "Rice Dishes",
    itemName: "Egg Rice",
    discription: "Egg Rice",
    imgUrl: "/images/Egg-Rice.jpg",
    price: 3.95,
  },
  {
    id: 45,
    catagoryName: "Rice Dishes",
    itemName: "Garlic & Onion Rice",
    discription: "Garlic & Onion Rice",
    imgUrl: "/images/Garlic-Onion-Rice.jpg",
    price: 3.95,
  },
  {
    id: 46,
    catagoryName: "Rice Dishes",
    itemName: "Lentil Rice",
    discription: "Lentil Rice",
    imgUrl: "/images/Lentil-Rice.jpg",
    price: 3.95,
  },
  {
    id: 47,
    catagoryName: "Rice Dishes",
    itemName: "Mushroom Rice",
    discription: "Mushroom Rice",
    imgUrl: "/images/Mushroom-Rice.jpg",
    price: 3.95,
  },
  {
    id: 48,
    catagoryName: "Rice Dishes",
    itemName: "Pilau Rice",
    discription: "Pilau Rice",
    imgUrl: "/images/Pilau-Rice.jpg",
    price: 3.5,
  },
  {
    id: 49,
    catagoryName: "Rice Dishes",
    itemName: "Special Fried Rice",
    discription: "Special Fried Rice",
    imgUrl: "/images/Special-Fried-Rice.jpg",
    price: 3.95,
  },
  {
    id: 50,
    catagoryName: "Rice Dishes",
    itemName: "Steamed Basmati Rice",
    discription: "Steamed Basmati Rice",
    imgUrl: "/images/Steamed-Basmati-Rice.jpg",
    price: 3.2,
  },
  {
    id: 51,
    catagoryName: "Rice Dishes",
    itemName: "Vegetable Rice",
    discription: "Vegetable Rice ",
    imgUrl: "/images/Vegetable-Rice.jpg",
    price: 3.95,
  },

  //   Tandoori Bread
  {
    id: 52,
    catagoryName: "Tandoori Bread",
    itemName: "Butter Naan",
    discription: "Butter Naan",
    imgUrl: "/images/Butter-Naan.jpg",
    price: 2.95,
  },
  {
    id: 53,
    catagoryName: "Tandoori Bread",
    itemName: "Chapatis ",
    discription: "Chapatis  ",
    imgUrl: "",
    price: 2.5,
  },
  {
    id: 54,
    catagoryName: "Tandoori Bread",
    itemName: "Cheese Naan ",
    discription: "Cheese Naan ",
    imgUrl: "/images/Cheese-Naan.jpg",
    price: 3.95,
  },
  {
    id: 55,
    catagoryName: "Tandoori Bread",
    itemName: "Chicken Tikka Naan",
    discription: "Chicken Tikka Naan",
    imgUrl: "/images/Chicken-Tikka-Naan.jpg",
    price: 3.95,
  },
  {
    id: 56,
    catagoryName: "Tandoori Bread",
    itemName: "Garlic Naan",
    discription: "Garlic Naan ",
    imgUrl: "/images/Garlic-Naan.jpg",
    price: 3.95,
  },
  {
    id: 57,
    catagoryName: "Tandoori Bread",
    itemName: "Keema Naan",
    discription: "Keema Naan ",
    imgUrl: "/images/Keema-Naan.jpg",
    price: 3.95,
  },
  {
    id: 58,
    catagoryName: "Tandoori Bread",
    itemName: "Papadum",
    discription: "All Padadums are served with chef's special dips",
    imgUrl: "",
    price: 1.2,
  },
  {
    id: 59,
    catagoryName: "Tandoori Bread",
    itemName: "Peshwari Naan",
    discription: "Peshwari Naan",
    imgUrl: "/images/Peshwari-Naan.jpg",
    price: 3.95,
  },
  {
    id: 60,
    catagoryName: "Tandoori Bread",
    itemName: "Plain Naan",
    discription: "Plain Naan",
    imgUrl: "/images/Plain-Naan.jpg",
    price: 2.95,
  },
  {
    id: 61,
    catagoryName: "Tandoori Bread",
    itemName: "Rocket Naan",
    discription: "Very spicy, made with cheese & chili flakes",
    imgUrl: "",
    price: 3.95,
  },
  {
    id: 62,
    catagoryName: "Tandoori Bread",
    itemName: "Stuffed Paratha (Mix Veg)",
    discription: "Stuffed Paratha (Mix Veg)",
    imgUrl: "/images/Stuffed-Paratha-(Mix Veg).jpg",
    price: 3.95,
  },
  {
    id: 63,
    catagoryName: "Tandoori Bread",
    itemName: "Tandoori Lachha Paratha ",
    discription: "Tandoori Lachha Paratha ",
    imgUrl: "",
    price: 3.5,
  },
  {
    id: 64,
    catagoryName: "Tandoori Bread",
    itemName: "Tandoori Roti",
    discription: "Tandoori Roti",
    imgUrl: "",
    price: 3.5,
  },
];
export default menu;
